apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp2-rc
spec:
   replicas: 3
   selector:
     app: myjavaapp2
     version: 2.7.2
   template:
     metadata:
       labels:
         app: myjavaapp2
         version: 2.7.2
     spec:
       containers:
        - name: myjavaapp-container
          image: maha4iac/mahaonlinestore:2
          ports:
          - containerPort: 8080