apiVersion: v1
kind: Service
metadata:
  name: myjavaapp2-svc
  labels:
    app: myjavaapp2
    version: 2.7.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31000
    protocol: TCP
  selector:
    app: myjavaapp2
    version: 2.7.2